fix grammar
aykutkardas/regexlearn.com pull request #114
Opened 2021-12-17 16:21 UTC by Laplacence

2021-12-17 17:40 UTC, aykutkardas commented
What do you think of these fixes? @isPoto

2021-12-18 02:32 UTC, isPoto requested changes
I have made some improvements for better grammatical understanding. @aykutkardas

2021-12-18 02:32 UTC, isPoto commented on src/localization/zh-cn/learn.json
> -  "examples.quantifierMin.description": "用 `{}` 编写表达式，匹配文本中位数至少为 `2` 的阿拉伯数字。",
匹配文本中，位数至少为 `2` 的阿拉伯数字

2021-12-18 02:32 UTC, isPoto commented on src/localization/zh-cn/learn.json
> -  "examples.quantifierRange.description": "用 `{}` 编写表达式，匹配文本中位数为 `1` 至 `4` 的阿拉伯数字。",
匹配文本中，位数为 `1` 至 `4` 的阿拉伯数字

2021-12-18 02:39 UTC, Laplacence commented on src/localization/zh-cn/learn.json
> -  "examples.quantifierMin.description": "用 `{}` 编写表达式，匹配文本中位数至少为 `2` 的阿拉伯数字。",
这一部分为`{}`的使用练习，去掉会不会产生一些歧义？

2021-12-18 02:43 UTC, Laplacence commented on src/localization/zh-cn/learn.json
> -  "examples.quantifierMin.description": "用 `{}` 编写表达式，匹配文本中位数至少为 `2` 的阿拉伯数字。",
个人感觉，位数单独拿出来放在前面有点不太适合中文语境。

2021-12-18 02:44 UTC, isPoto requested changes
My IT friend suggested me make a new copy of Contributor that is easy for you to adopt

2021-12-18 02:44 UTC, isPoto commented on src/localization/zh-cn/learn.json
> +  "examples.quantifierMin.description": "用 `{}` 编写表达式，匹配文本中至少为 `2` 位阿拉伯数字。",
```suggestion
  "examples.quantifierMin.description": "用 `{}` 编写表达式，匹配文本中，位数至少为 `2` 的阿拉伯数字。",
```

2021-12-18 02:44 UTC, isPoto commented on src/localization/zh-cn/learn.json
> +  "examples.quantifierRange.description": "用 `{}` 编写表达式，匹配文本中 `1` 至 `4` 位阿拉伯数字。",
```suggestion
  "examples.quantifierRange.description": "用 `{}` 编写表达式，匹配文本中，位数为 `1` 至 `4` 的阿拉伯数字。",
```

2021-12-18 02:48 UTC, shugen002 commented on src/localization/zh-cn/learn.json
> -  "examples.quantifierMin.description": "用 `{}` 编写表达式，匹配文本中位数至少为 `2` 的阿拉伯数字。",
确实，一般很少会说位数。

2021-12-18 03:38 UTC, isPoto reviewed
Agreed on one change, plus there's a discussion on translation, and I look forward to a better translated version being submitted.

2021-12-18 03:38 UTC, isPoto commented on src/localization/zh-cn/learn.json
> -  "examples.quantifier.description": "用 `{}` 编写表达式，匹配文本中的 `4` 位阿拉伯数字。",
Agree to the changes

2021-12-18 03:47 UTC, Laplacence commented on src/localization/zh-cn/learn.json
> -  "examples.quantifier.description": "用 `{}` 编写表达式，匹配文本中的 `4` 位阿拉伯数字。",
LGTM

2021-12-18 10:20 UTC, bxb100 commented
BTW, why not using `个`
example: `a{3,}` explain: "至少三个 a"

2021-12-19 12:01 UTC, Laplacence commented
@bxb100 
如果可以使用‘位’这样的量词，那我们就尽量不使用‘个’这样通用的量词。

2021-12-20 07:47 UTC, isPoto commented
https://zh.wikipedia.org/wiki/%E6%95%B0%E4%BD%8D_(%E6%95%B0%E5%AD%A6)

According to the common Chinese terminology for numbers, `位' should be used instead of `个'

Considering that some users have urged me to fix the errors mentioned in this version of the PR, I am fixing and launching the PR first. i want to fix the obvious errors first, and as for the translation wording, I want to put aside the controversy. It is more important for users to experience the correct translation as soon as possible

2021-12-20 18:57 UTC, aykutkardas commented
Thanks for your contribution. @Laplacence 

I've accepted @isPoto 's pull request for now. Please keep reviewing and making improvements to the translation.

2021-12-20 18:57 UTC, closed without merging